In [1]:
import tensorflow._api.v2.compat.v1 as tf

In [8]:
a = tf.constant([[1,2,3],[4,5,6]])
b = tf.constant([2,1], tf.int32)

In [9]:
tf.tile(a,b)

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [16]:
# roi features:
ref_features = tf.constant([[[1,11,111],[2,22,222],[3,33,333]],
                            [[4,44,444],[5,55,555],[6,66,666]],
                            [[7,7,777],[8,88,888],[9,99,999]],
                            [[21,22,23],[31,32,33],[41,42,43]]])
ref_features

<tf.Tensor: shape=(4, 3, 3), dtype=int32, numpy=
array([[[  1,  11, 111],
        [  2,  22, 222],
        [  3,  33, 333]],

       [[  4,  44, 444],
        [  5,  55, 555],
        [  6,  66, 666]],

       [[  7,   7, 777],
        [  8,  88, 888],
        [  9,  99, 999]],

       [[ 21,  22,  23],
        [ 31,  32,  33],
        [ 41,  42,  43]]], dtype=int32)>

In [17]:
features = tf.constant([[[1,11,111],[2,22,222],[3,33,333]],
                            [[4,44,444],[5,55,555],[6,66,666]],
                            [[7,7,777],[8,88,888],[9,99,999]],
                            [[21,22,23],[31,32,33],[41,42,43]]])

In [19]:
tiled = tf.tile(ref_features, [features.shape[0],1,1])

In [22]:
tf.concat((tiled,features), axis=1)

InvalidArgumentError: ConcatOp : Dimensions of inputs should match: shape[0] = [16,3,3] vs. shape[1] = [4,3,3] [Op:ConcatV2] name: concat

In [29]:
mesh_features = tf.constant(1, shape=(49))
mesh_features

<tf.Tensor: shape=(49,), dtype=int32, numpy=
array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1], dtype=int32)>

In [30]:
expanded = tf.expand_dims(mesh_features,axis=0)
expanded

<tf.Tensor: shape=(1, 49), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1]], dtype=int32)>

In [34]:
reshap = tf.reshape(expanded, [-1, 7,7])

In [35]:
tf.size(reshap)

<tf.Tensor: shape=(), dtype=int32, numpy=49>

In [32]:
import numpy as np

In [33]:
np.sqrt(32)

5.656854249492381